# -*- coding: utf-8 -*-
"""Prompt exports used by VideoAtlasAgent."""

from .video_atlas_prompts import (
    CONTEXT_GENERATION_PROMPT,
    TASK_DERIVATION_PROMPT,
    TITLE_GENERATION_PROMPT,
    VIDEO_GLOBAL_PROMPT,
    VIDEO_PROBE_PROMPT,
    VIDEO_SEGMENT_PROMPT,
)

__all__ = [
    "VIDEO_SEGMENT_PROMPT",
    "CONTEXT_GENERATION_PROMPT",
    "TITLE_GENERATION_PROMPT",
    "TASK_DERIVATION_PROMPT",
    "VIDEO_GLOBAL_PROMPT",
    "VIDEO_PROBE_PROMPT",
]
