# -*- coding: utf-8 -*-
"""Prompt exports used by the atlas agents."""

from .canonical_prompts import (
    BOUNDARY_DETECTION_PROMPT,
    CAPTION_GENERATION_PROMPT,
    PLANNER_PROMPT,
    VIDEO_GLOBAL_PROMPT,
)
from .derived_prompts import (
    DERIVED_CANDIDATE_PROMPT,
    DERIVED_CAPTION_PROMPT,
    DERIVED_GROUNDING_PROMPT,
)

__all__ = [
    "BOUNDARY_DETECTION_PROMPT",
    "CAPTION_GENERATION_PROMPT",
    "DERIVED_CANDIDATE_PROMPT",
    "DERIVED_CAPTION_PROMPT",
    "DERIVED_GROUNDING_PROMPT",
    "VIDEO_GLOBAL_PROMPT",
    "PLANNER_PROMPT",
]
